name: Test Bot

on:
workflow_dispatch:

# Add concurrency group to prevent parallel runs
concurrency:
group: ${{ github.workflow }}
cancel-in-progress: false

# Daily job to run the simple forecast bot
jobs:
forecast_job:
runs-on: ubuntu-latest # determines the machine that will run the job - keep as is
steps: # sets up the steps that will be run in order
# setup repository with all necessary dependencies - keep as is
- name: Check out repository
- uses: actions/setup-python@v4
- name: Install poetry
uses: snok/install-poetry@v1
with:
virtualenvs-create: true
virtualenvs-in-project: true
installer-parallel: true
# Adding the below will make the workflow faster, but will mean you don't automatically get updates from forecasting-tools and other packages
# - name: Load cached venv
#   id: cached-poetry-dependencies
#   uses: actions/cache@v4
#   with:
#     path: .venv
#     key: venv-runner.os−{{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
- name: Install dependencies
run: poetry install --no-interaction --no-root
- name: Run bot
run: |
poetry run python main.py --mode test_questions
# this reads the environment variables from the github repository.
# Store under Settings --> Secrets and variables --> Actions
env:
METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
